nome = str(input("Digite seu nome: ")).strip()
print("Analisando seu nome...")
print("Seu nome em letras maiúsculas fica: {}".format(nome.upper()))
print("Seu nome em letras minúsculas fica: {}".format(nome.lower()))
print("Seu nome tem ao todo: {} letras".format(len(nome) - nome.count(" ")))
#print("Seu primeiro nome tem {} letras".format(nome.find(" ")))
separa = nome.split()
print("Seu primeiro nome é {} e ele tem {} letras".format(separa[0], len(separa[0])))
